
c = "some context that logs on exit"

f = fun() {
    with (c) {
        # return should exit the outer function
        # but it should still allow c to run first
        return
    }
    "not reached".print
}

f()
